### ISSUE TITLE
picamera.exc.PiCameraMMALError: Failed to create MMAL component b'vc.camera_info': I/O error

### ISSUE THREAD

**Issue by iball8** [resin-io-projects/resin-rpi-python-picamera#13]
Using Raspberry Pi 3 Model B with Raspberry Pi camera v1.3 5MP. 
Not sure why I'm getting error in the title.

**Docker File**
FROM resin/%%RESIN_MACHINE_NAME%%-python

ENV INITSYSTEM on

RUN sudo apt-get update
RUN sudo apt-get install python3 python3-dev python3-pip python3-rpi.gpio git libraspberrypi-bin python3-smbus
RUN READTHEDOCS=True pip3 install picamera
RUN git clone https://github.com/adafruit/Adafruit_Python_GPIO.git \
&& cd Adafruit_Python_GPIO \
&& sudo python3 setup.py install
RUN git clone https://github.com/aws/aws-iot-device-sdk-python.git \
&& cd aws-iot-device-sdk-python \
&& sudo python3 setup.py install

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["bash","start.sh"]

**start.sh**
modprobe i2c-dev && modprobe v4l2_common && python3 /usr/src/app/main.py 

**main.py**
import picamera
camera = picamera.PiCamera()
def Camera():
		camera.resolution = (1024, 768)
		camera.start_preview()
		# Camera warm-up time
		time.sleep(2)
		camera.capture('/data/image.jpg')
		print("Picture Taken")

while True:
	        Camera():
                time.sleep(60)

**LOGS**
17.04.18 00:59:14 (+0000) Traceback (most recent call last):
17.04.18 00:59:14 (+0000)   File "/usr/src/app/main.py", line 107, in <module>
17.04.18 00:59:14 (+0000)     camera = picamera.PiCamera()
17.04.18 00:59:14 (+0000)   File "/usr/local/lib/python3.4/dist-packages/picamera/camera.py", line 367, in __init__
17.04.18 00:59:14 (+0000)     with mo.MMALCameraInfo() as camera_info:
17.04.18 00:59:14 (+0000)   File "/usr/local/lib/python3.4/dist-packages/picamera/mmalobj.py", line 2346, in __init__
17.04.18 00:59:14 (+0000)     super(MMALCameraInfo, self).__init__()
17.04.18 00:59:14 (+0000)   File "/usr/local/lib/python3.4/dist-packages/picamera/mmalobj.py", line 633, in __init__
17.04.18 00:59:14 (+0000)     prefix="Failed to create MMAL component %s" % self.component_type)
17.04.18 00:59:14 (+0000)   File "/usr/local/lib/python3.4/dist-packages/picamera/exc.py", line 184, in mmal_check
17.04.18 00:59:14 (+0000)     raise PiCameraMMALError(status, prefix)
17.04.18 00:59:14 (+0000) picamera.exc.PiCameraMMALError: Failed to create MMAL component b'vc.camera_info': I/O error

**Comment by iball8** [comment]
Solved! Needed to change environmental variables.
RESIN_HOST_CONFIG_gpu_mem to 128
RESIN_HOST_CONFIG_start_x to 1 in the fleet or device configuration.
