### ISSUE TITLE
picamera 1.13 would break compiling

### ISSUE THREAD

**Issue by xoul** [resin-io-projects/resin-rpi-python-picamera#8]
Can't push the application to my Raspberry Pi 3 because of something wrong with the latest release of the picamera PIP module:

```
[Build]    Collecting picamera (from -r /requirements.txt (line 1))
[Build]      Downloading picamera-1.13.tar.gz (143kB)
[Build]    Building wheels for collected packages: picamera
[...]
[Build]      running install
[Build]      Traceback (most recent call last):
[Build]        File "<string>", line 1, in <module>
[Build]        File "/tmp/pip-build-MH0Xe8/picamera/setup.py", line 145, in <module>
[Build]          main()
[Build]        File "/tmp/pip-build-MH0Xe8/picamera/setup.py", line 140, in main
[Build]          cmdclass             = {'install': CustomInstallCommand},
[Build]        File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
[Build]          dist.run_commands()
[Build]        File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
[Build]          self.run_command(cmd)
[Build]        File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
[Build]          cmd_obj.run()
[Build]        File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 215, in run
[Build]          self.run_command('install')
[Build]        File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
[Build]          self.distribution.run_command(command)
[Build]        File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
[Build]          cmd_obj.run()
[Build]        File "/tmp/pip-build-MH0Xe8/picamera/setup.py", line 111, in run
[Build]          raise ValueError('Unable to determine if this system is a Raspberry Pi')
[Build]      ValueError: Unable to determine if this system is a Raspberry Pi
```

Version 1.13 of picamera comes with CustomInstallCommand() inside on setup.py. This would parse /proc/cpuinfo in search of an "Hardware:" string referring to known Raspberry Pi hardware platforms.
But Resin.io build system do not run on RPi3, so...

I've lazily changed the content of requirements.txt to

`picamera < 1.13`

**Comment by kipe** [comment]
adding `ENV READTHEDOCS True` to the Dockerfile, before installing picamera should be enough.

**Comment by jdaniellhebert** [comment]
I can confirm that this works.

**Comment by craigmulligan** [comment]
Huh, that's strange, so does `READTHEDOCS` just raise a flag to skip the `CustomInstallCommand` function? Happy to accept a PR if either of you have time to push the fix.

**Comment by kipe** [comment]
It disables the "running on RPi" -detection: https://github.com/waveform80/picamera/blob/master/setup.py#L98

The detection relies on checking the CPU model, which of course doesn't match to RPi when running on the build system.

**Comment by un-lock-me** [comment]
I faced with this error, no success to get it run.can you please explain what did you do, 
where should I put this `ENV READTHEDOCS True`?

**Comment by kipe** [comment]
@saria85 just add it to the `Dockerfile`, before installing the picamera package.

**Comment by ACONCEPT** [comment]
I dont get why everyones trolling on this, I got the same problem and I've been reading the docs and don't find the answer.
